export { default as About } from './about'
export { default as PortfolioNavbar } from './navbar'
export { default as Hero } from './hero'
export { default as Portfolio } from './portfolio'
export { default as Contact } from './contact'
export { default as Resume } from './resume'
export { default as Footer } from './footer'